@Host = http://localhost:9999
@CustomerId = 1

GET {{Host}}/clientes/{{CustomerId}}/extrato
Accept: application/json

###

POST {{Host}}/clientes/{{CustomerId}}/transacoes
Content-Type: application/json

{
    "valor" : 100,
    "tipo" : "c",
    "descricao" : "pix 2"
}
